# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: CI

on:
  schedule:
    - cron: '10 22 * * *'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch
        run: python main.py

      - name: Commit + Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "ci: update instances"
            git push origin HEAD:main
          fi

      - name: Mirror to Codeberg
        if: success()
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: git push https://manerakai:${CODEBERG_TOKEN}@codeberg.org/LibRedirect/instances.git HEAD:main
